// TOEIC에 자주 나오는 구동사/숙어 모음.
// 이런 표현은 Datamuse에 정의가 없거나(예: "manage to"), 번역 API가 단어 하나씩 직역해서
// 엉뚱한 결과("manage to" -> "다음으로 관리")를 내는 경우가 많아 직접 정리해 두었다.
// keywords에 있는 표현과 입력값이 일치하거나 포함 관계면 매칭된다 (grammar-data.js와 같은 방식).
const TOEIC_IDIOMS = [
  {
    keywords: ["manage to"],
    ko: "간신히 ~해내다",
    en: "to succeed in doing something, especially something difficult",
    example: "She managed to finish the report before the deadline.",
    exampleKo: "그녀는 마감 전에 간신히 보고서를 끝냈다.",
  },
  {
    keywords: ["in charge of"],
    ko: "~을 책임지는, ~을 맡은",
    en: "responsible for managing or controlling something",
    example: "Mr. Kim is in charge of the marketing department.",
    exampleKo: "김 씨는 마케팅 부서를 맡고 있다.",
  },
  {
    keywords: ["be in charge of"],
    ko: "~을 책임지고 있다",
    en: "to be responsible for managing or controlling something",
    example: "She is in charge of hiring new employees.",
    exampleKo: "그녀는 신입 사원 채용을 담당하고 있다.",
  },
  {
    keywords: ["look forward to"],
    ko: "~을 기대하다, 고대하다",
    en: "to feel happy and excited about something that is going to happen",
    example: "We look forward to hearing from you soon.",
    exampleKo: "곧 연락 주시기를 기대하겠습니다.",
  },
  {
    keywords: ["be responsible for"],
    ko: "~에 책임이 있다",
    en: "having control over or accountable for something",
    example: "Each manager is responsible for their own team's budget.",
    exampleKo: "각 관리자는 자기 팀의 예산에 책임이 있다.",
  },
  {
    keywords: ["comply with"],
    ko: "~을 준수하다, 따르다",
    en: "to act according to a rule, order, or request",
    example: "All employees must comply with the new safety regulations.",
    exampleKo: "모든 직원은 새로운 안전 규정을 준수해야 한다.",
  },
  {
    keywords: ["be eligible for"],
    ko: "~할 자격이 있다",
    en: "to have the right to do or receive something",
    example: "Employees are eligible for a bonus after one year.",
    exampleKo: "직원들은 1년 후 보너스를 받을 자격이 있다.",
  },
  {
    keywords: ["get in touch with"],
    ko: "~와 연락하다",
    en: "to communicate with someone, especially by phone or email",
    example: "Please get in touch with our support team.",
    exampleKo: "저희 지원팀에 연락해 주세요.",
  },
  {
    keywords: ["take advantage of"],
    ko: "~을 이용하다, 활용하다",
    en: "to make good use of an opportunity",
    example: "Customers can take advantage of the discount this week.",
    exampleKo: "고객들은 이번 주에 할인을 이용할 수 있다.",
  },
  {
    keywords: ["be aware of"],
    ko: "~을 알고 있다, 인지하다",
    en: "to know that something exists or is happening",
    example: "Please be aware of the schedule change.",
    exampleKo: "일정 변경을 인지해 주시기 바랍니다.",
  },
  {
    keywords: ["be committed to"],
    ko: "~에 전념하다, 헌신하다",
    en: "dedicated to a cause, activity, or job",
    example: "The company is committed to reducing waste.",
    exampleKo: "그 회사는 폐기물 감소에 전념하고 있다.",
  },
  {
    keywords: ["be equipped with"],
    ko: "~을 갖추고 있다",
    en: "to have the necessary tools or features",
    example: "Every room is equipped with high-speed internet.",
    exampleKo: "모든 객실에는 고속 인터넷이 갖춰져 있다.",
  },
  {
    keywords: ["be entitled to"],
    ko: "~을 받을 자격이 있다, ~할 권리가 있다",
    en: "to have a legal or official right to something",
    example: "Full-time staff are entitled to paid leave.",
    exampleKo: "정규직 직원은 유급 휴가를 받을 자격이 있다.",
  },
  {
    keywords: ["be subject to"],
    ko: "~의 대상이다, ~될 수 있다",
    en: "likely to be affected by or dependent on something",
    example: "Prices are subject to change without notice.",
    exampleKo: "가격은 예고 없이 변경될 수 있다.",
  },
  {
    keywords: ["be capable of"],
    ko: "~할 능력이 있다",
    en: "having the ability or qualities needed to do something",
    example: "The new machine is capable of processing twice as fast.",
    exampleKo: "새 기계는 두 배 빠르게 처리할 수 있는 능력이 있다.",
  },
  {
    keywords: ["on behalf of"],
    ko: "~을 대신하여, ~을 대표하여",
    en: "as the representative of someone",
    example: "I am writing on behalf of the sales team.",
    exampleKo: "영업팀을 대신하여 이 글을 씁니다.",
  },
  {
    keywords: ["in accordance with"],
    ko: "~에 따라, ~에 부합하여",
    en: "in a way that follows a rule, law, or agreement",
    example: "The refund was processed in accordance with company policy.",
    exampleKo: "환불은 회사 정책에 따라 처리되었다.",
  },
  {
    keywords: ["with regard to", "with regards to"],
    ko: "~와 관련하여, ~에 관해",
    en: "concerning or about a particular subject",
    example: "With regard to your inquiry, we will respond within 24 hours.",
    exampleKo: "문의하신 내용과 관련하여 24시간 이내에 답변드리겠습니다.",
  },
  {
    keywords: ["as a result of"],
    ko: "~의 결과로, ~때문에",
    en: "because of something",
    example: "Sales increased as a result of the new campaign.",
    exampleKo: "새 캠페인 덕분에 매출이 증가했다.",
  },
  {
    keywords: ["prior to"],
    ko: "~에 앞서, ~전에",
    en: "before something in time",
    example: "Please arrive prior to the start of the meeting.",
    exampleKo: "회의 시작 전에 도착해 주세요.",
  },
  {
    keywords: ["due to"],
    ko: "~때문에, ~로 인해",
    en: "because of something",
    example: "The flight was delayed due to bad weather.",
    exampleKo: "항공편이 악천후로 인해 지연되었다.",
  },
  {
    keywords: ["keep track of"],
    ko: "~을 파악하다, 기록하다",
    en: "to keep a record of or stay informed about something",
    example: "This app helps you keep track of your expenses.",
    exampleKo: "이 앱은 지출을 파악하는 데 도움이 된다.",
  },
  {
    keywords: ["come up with"],
    ko: "~을 생각해내다, 제시하다",
    en: "to think of an idea or plan",
    example: "The team came up with a new solution.",
    exampleKo: "그 팀은 새로운 해결책을 생각해냈다.",
  },
  {
    keywords: ["carry out"],
    ko: "~을 수행하다, 실시하다",
    en: "to perform or complete a task",
    example: "The survey was carried out last month.",
    exampleKo: "그 설문 조사는 지난달에 실시되었다.",
  },
  {
    keywords: ["result in"],
    ko: "~을 초래하다, ~라는 결과를 낳다",
    en: "to cause something to happen",
    example: "The merger resulted in significant cost savings.",
    exampleKo: "그 합병은 상당한 비용 절감이라는 결과를 낳았다.",
  },
];
